version: '3.3'
services:

  frontend:
    image: andrisreskais/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  api:
    image: andrisreskais/foodgram
    restart: always
    volumes:
      - static_value:/api/static/
      - media_value:/api/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - ../static:/var/html/static/
      - media_value:/var/html/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - frontend
      - api

volumes:
  postgres_data:
  static_value:
  media_value:
