version: '3.3'
services:

  db:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  api:
    image: andrisreskais/foodgram
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - ../data/:/app/data/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: andrisreskais/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - api

  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - /static_value:/var/html/static/
      - /media_value:/var/html/media/
    depends_on:
      - frontend
      - api

volumes:
  postgres_data:
  static_value:
  media_value:
