# Generated by Django 4.0.2 on 2022-02-11 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_favoriterecipes_user_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriterecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='recipe.recipe'),
        ),
    ]
