# Generated by Django 4.0.2 on 2022-02-12 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_foodgramuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Логин должен содержать ТОЛЬКО: буквы/цифры(с учетом регистра), а также символы: .@+-', regex='^[\\w.@+-]+$')]),
        ),
    ]
